name: Trigger

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Script Workflow 1
        uses: ./.github/workflows/generator1.yml

      - name: Trigger Script Workflow 2
        uses: ./.github/workflows/generator2.yml

      - name: Trigger Script Workflow 3
        uses: ./.github/workflows/generator3.yml

      - name: Trigger Script Workflow 4
        uses: ./.github/workflows/generator4.yml

      - name: Trigger Script Workflow 5
        uses: ./.github/workflows/generator5.yml

      - name: Trigger Script Workflow 6
        uses: ./.github/workflows/generator6.yml

      - name: Trigger Script Workflow 7
        uses: ./.github/workflows/generator7.yml

      - name: Trigger Script Workflow 8
        uses: ./.github/workflows/generator8.yml
